$ANSIBLE_VAULT;1.1;AES256
31393234616438393566376438343362386439613366313364616539613838626661303764326330
6162653935376338663635336461643862623438636130310a396565666437643665303166326337
33326461343530336431386662343661623362326631356364623132653233633732366638366666
6239313031633631330a313234656635303963353563633364616436386565633663333364653635
33383536306365393034343034343032636536386563323236636131613662393735343436626230
32356634303066633665633332646231323338393566353137613132343039663466373037326639
38343439396334623638663938663135633165626562663536313564646666613862303036396262
31376134366332386665623931313064666132343532616132363530663136666466303339616536
63363866333365323236656565383934626466653064363432663261633231343238
