$ANSIBLE_VAULT;1.1;AES256
63386531663731353666363162356637363965303461653364656435326338333037623462323663
6335643366623835353634373830633336303334386463300a353134303534646433333038666334
39656366613433313135393237643539333136303966333431376338376335663230313362383034
3164343765353061370a396166323739376335373437343361373231663962313061663964613339
35313966323862313963323130373532636232306634643764616263363632626332653765616133
63326339333035373531623733326137386466373165643835306462383035326439643631303831
30336263356332313137313539623938326662653061343764343031623736393335653535333237
37656462323633646630353735386131326466313935633566326638336436366635313664303934
61326466633164386537663637396538623630613334656265643430343239313936
